info:
  contact: {}
paths:
  /books:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
      summary: Get a list of Books
swagger: "2.0"
