definitions:
  models.Book:
    properties:
      author:
        type: string
      id:
        type: string
      quantity:
        type: integer
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /books:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
      summary: Get a list of Books
swagger: "2.0"
